title: .Net Slave
description: How to avoid it

url: http://dotnetslave.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   twitter: reiten_schnell
   email: alina542.1@gmail.com

google_analytics: "UA-66532118-1"
